[phases.setup]
cmds = ["mkdir -p /app/staticfiles"]

[phases.build]
cmds = ["python manage.py collectstatic --noinput"]

[phases.start]
cmd = "python manage.py migrate && gunicorn gestion_pymes.wsgi --log-file -"