# Generated by Django 5.0.6 on 2026-05-11 23:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cartera', '0001_initial'),
        ('ventas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='abono',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abonos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deuda',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deudas', to='cartera.cliente'),
        ),
        migrations.AddField(
            model_name='deuda',
            name='venta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deuda', to='ventas.venta'),
        ),
        migrations.AddField(
            model_name='abono',
            name='deuda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonos', to='cartera.deuda'),
        ),
    ]
